/*
 * PTV Open Api version 10
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.ptv.client.model.V10VmOpenApiServiceServiceChannel;
import fi.metatavu.ptv.client.model.V4VmOpenApiFintoItem;
import fi.metatavu.ptv.client.model.V4VmOpenApiLaw;
import fi.metatavu.ptv.client.model.V6VmOpenApiServiceOrganization;
import fi.metatavu.ptv.client.model.V7VmOpenApiFintoItemWithDescription;
import fi.metatavu.ptv.client.model.V9VmOpenApiServiceVoucher;
import fi.metatavu.ptv.client.model.VmOpenApiArea;
import fi.metatavu.ptv.client.model.VmOpenApiLanguageItem;
import fi.metatavu.ptv.client.model.VmOpenApiLocalizedListItem;
import fi.metatavu.ptv.client.model.VmOpenApiServiceServiceCollection;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * OPEN API V10 - View Model of service
 */
@ApiModel(description = "OPEN API V10 - View Model of service")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-08T12:51:13.642+03:00")
public class V10VmOpenApiService {
  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("sourceId")
  private String sourceId = null;

  @JsonProperty("generalDescriptionId")
  private UUID generalDescriptionId = null;

  @JsonProperty("subType")
  private String subType = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("fundingType")
  private String fundingType = null;

  @JsonProperty("serviceNames")
  private List<VmOpenApiLocalizedListItem> serviceNames = null;

  @JsonProperty("serviceChargeType")
  private String serviceChargeType = null;

  @JsonProperty("areaType")
  private String areaType = null;

  @JsonProperty("areas")
  private List<VmOpenApiArea> areas = null;

  @JsonProperty("serviceDescriptions")
  private List<VmOpenApiLocalizedListItem> serviceDescriptions = null;

  @JsonProperty("languages")
  private List<String> languages = null;

  @JsonProperty("serviceClasses")
  private List<V7VmOpenApiFintoItemWithDescription> serviceClasses = null;

  @JsonProperty("ontologyTerms")
  private List<V4VmOpenApiFintoItem> ontologyTerms = null;

  @JsonProperty("targetGroups")
  private List<V4VmOpenApiFintoItem> targetGroups = null;

  @JsonProperty("lifeEvents")
  private List<V4VmOpenApiFintoItem> lifeEvents = null;

  @JsonProperty("industrialClasses")
  private List<V4VmOpenApiFintoItem> industrialClasses = null;

  @JsonProperty("legislation")
  private List<V4VmOpenApiLaw> legislation = null;

  @JsonProperty("keywords")
  private List<VmOpenApiLanguageItem> keywords = null;

  @JsonProperty("requirements")
  private List<VmOpenApiLanguageItem> requirements = null;

  @JsonProperty("serviceChannels")
  private List<V10VmOpenApiServiceServiceChannel> serviceChannels = null;

  @JsonProperty("organizations")
  private List<V6VmOpenApiServiceOrganization> organizations = null;

  @JsonProperty("serviceVouchersInUse")
  private Boolean serviceVouchersInUse = null;

  @JsonProperty("serviceVouchers")
  private List<V9VmOpenApiServiceVoucher> serviceVouchers = null;

  @JsonProperty("serviceCollections")
  private List<VmOpenApiServiceServiceCollection> serviceCollections = null;

  @JsonProperty("publishingStatus")
  private String publishingStatus = null;

  @JsonProperty("modified")
  private @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified = null;

  @JsonProperty("responsibleSoteOrganization")
  private String responsibleSoteOrganization = null;

  public V10VmOpenApiService id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Entity identifier.
   * @return id
  **/
  @ApiModelProperty(value = "Entity identifier.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public V10VmOpenApiService sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * External system identifier for the entity. User needs to be logged in to be able to get/set value.
   * @return sourceId
  **/
  @ApiModelProperty(value = "External system identifier for the entity. User needs to be logged in to be able to get/set value.")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public V10VmOpenApiService generalDescriptionId(UUID generalDescriptionId) {
    this.generalDescriptionId = generalDescriptionId;
    return this;
  }

   /**
   * PTV identifier for linked general description.
   * @return generalDescriptionId
  **/
  @ApiModelProperty(value = "PTV identifier for linked general description.")
  public UUID getGeneralDescriptionId() {
    return generalDescriptionId;
  }

  public void setGeneralDescriptionId(UUID generalDescriptionId) {
    this.generalDescriptionId = generalDescriptionId;
  }

  public V10VmOpenApiService subType(String subType) {
    this.subType = subType;
    return this;
  }

   /**
   * Service sub-type. It is used for SOTE and its taken from GeneralDescription&#39;s generalDescriptionType. Possible values are: PrescribedByFreedomOfChoiceAct, OtherPermissionGrantedSote.
   * @return subType
  **/
  @ApiModelProperty(value = "Service sub-type. It is used for SOTE and its taken from GeneralDescription's generalDescriptionType. Possible values are: PrescribedByFreedomOfChoiceAct, OtherPermissionGrantedSote.")
  public String getSubType() {
    return subType;
  }

  public void setSubType(String subType) {
    this.subType = subType;
  }

  public V10VmOpenApiService type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Service type. Possible values are: Service, PermitOrObligation or ProfessionalQualification. In version 7 Service, PermissionAndObligation or ProfessionalQualifications.
   * @return type
  **/
  @ApiModelProperty(value = "Service type. Possible values are: Service, PermitOrObligation or ProfessionalQualification. In version 7 Service, PermissionAndObligation or ProfessionalQualifications.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public V10VmOpenApiService fundingType(String fundingType) {
    this.fundingType = fundingType;
    return this;
  }

   /**
   * Service funding type. Possible values are: PubliclyFunded or MarketFunded.
   * @return fundingType
  **/
  @ApiModelProperty(value = "Service funding type. Possible values are: PubliclyFunded or MarketFunded.")
  public String getFundingType() {
    return fundingType;
  }

  public void setFundingType(String fundingType) {
    this.fundingType = fundingType;
  }

  public V10VmOpenApiService serviceNames(List<VmOpenApiLocalizedListItem> serviceNames) {
    this.serviceNames = serviceNames;
    return this;
  }

  public V10VmOpenApiService addServiceNamesItem(VmOpenApiLocalizedListItem serviceNamesItem) {
    if (this.serviceNames == null) {
      this.serviceNames = new ArrayList<VmOpenApiLocalizedListItem>();
    }
    this.serviceNames.add(serviceNamesItem);
    return this;
  }

   /**
   * List of localized service names. Possible type values are: Name, AlternativeName (in version 7 AlternateName).
   * @return serviceNames
  **/
  @ApiModelProperty(value = "List of localized service names. Possible type values are: Name, AlternativeName (in version 7 AlternateName).")
  public List<VmOpenApiLocalizedListItem> getServiceNames() {
    return serviceNames;
  }

  public void setServiceNames(List<VmOpenApiLocalizedListItem> serviceNames) {
    this.serviceNames = serviceNames;
  }

  public V10VmOpenApiService serviceChargeType(String serviceChargeType) {
    this.serviceChargeType = serviceChargeType;
    return this;
  }

   /**
   * Service charge type. Possible values are: Chargeable or FreeOfCharge.  In version 7: Charged or Free.  NOTE! If service charge type has been defined within attached statutory service general description, the charge type for service is ignored.
   * @return serviceChargeType
  **/
  @ApiModelProperty(value = "Service charge type. Possible values are: Chargeable or FreeOfCharge.  In version 7: Charged or Free.  NOTE! If service charge type has been defined within attached statutory service general description, the charge type for service is ignored.")
  public String getServiceChargeType() {
    return serviceChargeType;
  }

  public void setServiceChargeType(String serviceChargeType) {
    this.serviceChargeType = serviceChargeType;
  }

  public V10VmOpenApiService areaType(String areaType) {
    this.areaType = areaType;
    return this;
  }

   /**
   * Area type. Possible values are: Nationwide, NationwideExceptAlandIslands or LimitedType.  In version 7: WholeCountry, WholeCountryExceptAlandIslands, AreaType.
   * @return areaType
  **/
  @ApiModelProperty(value = "Area type. Possible values are: Nationwide, NationwideExceptAlandIslands or LimitedType.  In version 7: WholeCountry, WholeCountryExceptAlandIslands, AreaType.")
  public String getAreaType() {
    return areaType;
  }

  public void setAreaType(String areaType) {
    this.areaType = areaType;
  }

  public V10VmOpenApiService areas(List<VmOpenApiArea> areas) {
    this.areas = areas;
    return this;
  }

  public V10VmOpenApiService addAreasItem(VmOpenApiArea areasItem) {
    if (this.areas == null) {
      this.areas = new ArrayList<VmOpenApiArea>();
    }
    this.areas.add(areasItem);
    return this;
  }

   /**
   * List of service areas.
   * @return areas
  **/
  @ApiModelProperty(value = "List of service areas.")
  public List<VmOpenApiArea> getAreas() {
    return areas;
  }

  public void setAreas(List<VmOpenApiArea> areas) {
    this.areas = areas;
  }

  public V10VmOpenApiService serviceDescriptions(List<VmOpenApiLocalizedListItem> serviceDescriptions) {
    this.serviceDescriptions = serviceDescriptions;
    return this;
  }

  public V10VmOpenApiService addServiceDescriptionsItem(VmOpenApiLocalizedListItem serviceDescriptionsItem) {
    if (this.serviceDescriptions == null) {
      this.serviceDescriptions = new ArrayList<VmOpenApiLocalizedListItem>();
    }
    this.serviceDescriptions.add(serviceDescriptionsItem);
    return this;
  }

   /**
   * List of localized service descriptions. Possible type values are: Description, Summary, UserInstruction, ValidityTime, ProcessingTime, DeadLine, ChargeTypeAdditionalInfo, ServiceType.  In version 7: Description, ShortDescription, ServiceUserInstruction, ValidityTimeAdditionalInfo, ProcessingTimeAdditionalInfo, DeadLineAdditionalInfo, ChargeTypeAdditionalInfo, ServiceTypeAdditionalInfo.
   * @return serviceDescriptions
  **/
  @ApiModelProperty(value = "List of localized service descriptions. Possible type values are: Description, Summary, UserInstruction, ValidityTime, ProcessingTime, DeadLine, ChargeTypeAdditionalInfo, ServiceType.  In version 7: Description, ShortDescription, ServiceUserInstruction, ValidityTimeAdditionalInfo, ProcessingTimeAdditionalInfo, DeadLineAdditionalInfo, ChargeTypeAdditionalInfo, ServiceTypeAdditionalInfo.")
  public List<VmOpenApiLocalizedListItem> getServiceDescriptions() {
    return serviceDescriptions;
  }

  public void setServiceDescriptions(List<VmOpenApiLocalizedListItem> serviceDescriptions) {
    this.serviceDescriptions = serviceDescriptions;
  }

  public V10VmOpenApiService languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public V10VmOpenApiService addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<String>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * List of service languages.
   * @return languages
  **/
  @ApiModelProperty(value = "List of service languages.")
  public List<String> getLanguages() {
    return languages;
  }

  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }

  public V10VmOpenApiService serviceClasses(List<V7VmOpenApiFintoItemWithDescription> serviceClasses) {
    this.serviceClasses = serviceClasses;
    return this;
  }

  public V10VmOpenApiService addServiceClassesItem(V7VmOpenApiFintoItemWithDescription serviceClassesItem) {
    if (this.serviceClasses == null) {
      this.serviceClasses = new ArrayList<V7VmOpenApiFintoItemWithDescription>();
    }
    this.serviceClasses.add(serviceClassesItem);
    return this;
  }

   /**
   * List of service classes related to the service.
   * @return serviceClasses
  **/
  @ApiModelProperty(value = "List of service classes related to the service.")
  public List<V7VmOpenApiFintoItemWithDescription> getServiceClasses() {
    return serviceClasses;
  }

  public void setServiceClasses(List<V7VmOpenApiFintoItemWithDescription> serviceClasses) {
    this.serviceClasses = serviceClasses;
  }

  public V10VmOpenApiService ontologyTerms(List<V4VmOpenApiFintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
    return this;
  }

  public V10VmOpenApiService addOntologyTermsItem(V4VmOpenApiFintoItem ontologyTermsItem) {
    if (this.ontologyTerms == null) {
      this.ontologyTerms = new ArrayList<V4VmOpenApiFintoItem>();
    }
    this.ontologyTerms.add(ontologyTermsItem);
    return this;
  }

   /**
   * List of ontology terms related to the service.
   * @return ontologyTerms
  **/
  @ApiModelProperty(value = "List of ontology terms related to the service.")
  public List<V4VmOpenApiFintoItem> getOntologyTerms() {
    return ontologyTerms;
  }

  public void setOntologyTerms(List<V4VmOpenApiFintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
  }

  public V10VmOpenApiService targetGroups(List<V4VmOpenApiFintoItem> targetGroups) {
    this.targetGroups = targetGroups;
    return this;
  }

  public V10VmOpenApiService addTargetGroupsItem(V4VmOpenApiFintoItem targetGroupsItem) {
    if (this.targetGroups == null) {
      this.targetGroups = new ArrayList<V4VmOpenApiFintoItem>();
    }
    this.targetGroups.add(targetGroupsItem);
    return this;
  }

   /**
   * List of target groups related to the service.
   * @return targetGroups
  **/
  @ApiModelProperty(value = "List of target groups related to the service.")
  public List<V4VmOpenApiFintoItem> getTargetGroups() {
    return targetGroups;
  }

  public void setTargetGroups(List<V4VmOpenApiFintoItem> targetGroups) {
    this.targetGroups = targetGroups;
  }

  public V10VmOpenApiService lifeEvents(List<V4VmOpenApiFintoItem> lifeEvents) {
    this.lifeEvents = lifeEvents;
    return this;
  }

  public V10VmOpenApiService addLifeEventsItem(V4VmOpenApiFintoItem lifeEventsItem) {
    if (this.lifeEvents == null) {
      this.lifeEvents = new ArrayList<V4VmOpenApiFintoItem>();
    }
    this.lifeEvents.add(lifeEventsItem);
    return this;
  }

   /**
   * List of life events  related to the service.
   * @return lifeEvents
  **/
  @ApiModelProperty(value = "List of life events  related to the service.")
  public List<V4VmOpenApiFintoItem> getLifeEvents() {
    return lifeEvents;
  }

  public void setLifeEvents(List<V4VmOpenApiFintoItem> lifeEvents) {
    this.lifeEvents = lifeEvents;
  }

  public V10VmOpenApiService industrialClasses(List<V4VmOpenApiFintoItem> industrialClasses) {
    this.industrialClasses = industrialClasses;
    return this;
  }

  public V10VmOpenApiService addIndustrialClassesItem(V4VmOpenApiFintoItem industrialClassesItem) {
    if (this.industrialClasses == null) {
      this.industrialClasses = new ArrayList<V4VmOpenApiFintoItem>();
    }
    this.industrialClasses.add(industrialClassesItem);
    return this;
  }

   /**
   * List of industrial classes related to the service.
   * @return industrialClasses
  **/
  @ApiModelProperty(value = "List of industrial classes related to the service.")
  public List<V4VmOpenApiFintoItem> getIndustrialClasses() {
    return industrialClasses;
  }

  public void setIndustrialClasses(List<V4VmOpenApiFintoItem> industrialClasses) {
    this.industrialClasses = industrialClasses;
  }

  public V10VmOpenApiService legislation(List<V4VmOpenApiLaw> legislation) {
    this.legislation = legislation;
    return this;
  }

  public V10VmOpenApiService addLegislationItem(V4VmOpenApiLaw legislationItem) {
    if (this.legislation == null) {
      this.legislation = new ArrayList<V4VmOpenApiLaw>();
    }
    this.legislation.add(legislationItem);
    return this;
  }

   /**
   * List of laws related to the service.
   * @return legislation
  **/
  @ApiModelProperty(value = "List of laws related to the service.")
  public List<V4VmOpenApiLaw> getLegislation() {
    return legislation;
  }

  public void setLegislation(List<V4VmOpenApiLaw> legislation) {
    this.legislation = legislation;
  }

  public V10VmOpenApiService keywords(List<VmOpenApiLanguageItem> keywords) {
    this.keywords = keywords;
    return this;
  }

  public V10VmOpenApiService addKeywordsItem(VmOpenApiLanguageItem keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * List of localized service keywords.
   * @return keywords
  **/
  @ApiModelProperty(value = "List of localized service keywords.")
  public List<VmOpenApiLanguageItem> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<VmOpenApiLanguageItem> keywords) {
    this.keywords = keywords;
  }

  public V10VmOpenApiService requirements(List<VmOpenApiLanguageItem> requirements) {
    this.requirements = requirements;
    return this;
  }

  public V10VmOpenApiService addRequirementsItem(VmOpenApiLanguageItem requirementsItem) {
    if (this.requirements == null) {
      this.requirements = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.requirements.add(requirementsItem);
    return this;
  }

   /**
   * Localized service usage requirements (description of requirement).
   * @return requirements
  **/
  @ApiModelProperty(value = "Localized service usage requirements (description of requirement).")
  public List<VmOpenApiLanguageItem> getRequirements() {
    return requirements;
  }

  public void setRequirements(List<VmOpenApiLanguageItem> requirements) {
    this.requirements = requirements;
  }

  public V10VmOpenApiService serviceChannels(List<V10VmOpenApiServiceServiceChannel> serviceChannels) {
    this.serviceChannels = serviceChannels;
    return this;
  }

  public V10VmOpenApiService addServiceChannelsItem(V10VmOpenApiServiceServiceChannel serviceChannelsItem) {
    if (this.serviceChannels == null) {
      this.serviceChannels = new ArrayList<V10VmOpenApiServiceServiceChannel>();
    }
    this.serviceChannels.add(serviceChannelsItem);
    return this;
  }

   /**
   * List of linked service channels including relationship data.
   * @return serviceChannels
  **/
  @ApiModelProperty(value = "List of linked service channels including relationship data.")
  public List<V10VmOpenApiServiceServiceChannel> getServiceChannels() {
    return serviceChannels;
  }

  public void setServiceChannels(List<V10VmOpenApiServiceServiceChannel> serviceChannels) {
    this.serviceChannels = serviceChannels;
  }

  public V10VmOpenApiService organizations(List<V6VmOpenApiServiceOrganization> organizations) {
    this.organizations = organizations;
    return this;
  }

  public V10VmOpenApiService addOrganizationsItem(V6VmOpenApiServiceOrganization organizationsItem) {
    if (this.organizations == null) {
      this.organizations = new ArrayList<V6VmOpenApiServiceOrganization>();
    }
    this.organizations.add(organizationsItem);
    return this;
  }

   /**
   * List of organizations, responsible and producer organizations of the service.
   * @return organizations
  **/
  @ApiModelProperty(value = "List of organizations, responsible and producer organizations of the service.")
  public List<V6VmOpenApiServiceOrganization> getOrganizations() {
    return organizations;
  }

  public void setOrganizations(List<V6VmOpenApiServiceOrganization> organizations) {
    this.organizations = organizations;
  }

  public V10VmOpenApiService serviceVouchersInUse(Boolean serviceVouchersInUse) {
    this.serviceVouchersInUse = serviceVouchersInUse;
    return this;
  }

   /**
   * Indicates if service vouchers are used in the service.
   * @return serviceVouchersInUse
  **/
  @ApiModelProperty(value = "Indicates if service vouchers are used in the service.")
  public Boolean getServiceVouchersInUse() {
    return serviceVouchersInUse;
  }

  public void setServiceVouchersInUse(Boolean serviceVouchersInUse) {
    this.serviceVouchersInUse = serviceVouchersInUse;
  }

  public V10VmOpenApiService serviceVouchers(List<V9VmOpenApiServiceVoucher> serviceVouchers) {
    this.serviceVouchers = serviceVouchers;
    return this;
  }

  public V10VmOpenApiService addServiceVouchersItem(V9VmOpenApiServiceVoucher serviceVouchersItem) {
    if (this.serviceVouchers == null) {
      this.serviceVouchers = new ArrayList<V9VmOpenApiServiceVoucher>();
    }
    this.serviceVouchers.add(serviceVouchersItem);
    return this;
  }

   /**
   * List of service vouchers.
   * @return serviceVouchers
  **/
  @ApiModelProperty(value = "List of service vouchers.")
  public List<V9VmOpenApiServiceVoucher> getServiceVouchers() {
    return serviceVouchers;
  }

  public void setServiceVouchers(List<V9VmOpenApiServiceVoucher> serviceVouchers) {
    this.serviceVouchers = serviceVouchers;
  }

  public V10VmOpenApiService serviceCollections(List<VmOpenApiServiceServiceCollection> serviceCollections) {
    this.serviceCollections = serviceCollections;
    return this;
  }

  public V10VmOpenApiService addServiceCollectionsItem(VmOpenApiServiceServiceCollection serviceCollectionsItem) {
    if (this.serviceCollections == null) {
      this.serviceCollections = new ArrayList<VmOpenApiServiceServiceCollection>();
    }
    this.serviceCollections.add(serviceCollectionsItem);
    return this;
  }

   /**
   * List of service collections that the service has been linked to
   * @return serviceCollections
  **/
  @ApiModelProperty(value = "List of service collections that the service has been linked to")
  public List<VmOpenApiServiceServiceCollection> getServiceCollections() {
    return serviceCollections;
  }

  public void setServiceCollections(List<VmOpenApiServiceServiceCollection> serviceCollections) {
    this.serviceCollections = serviceCollections;
  }

  public V10VmOpenApiService publishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
    return this;
  }

   /**
   * Publishing status. Possible values are: Draft, Published, Deleted or Modified.
   * @return publishingStatus
  **/
  @ApiModelProperty(value = "Publishing status. Possible values are: Draft, Published, Deleted or Modified.")
  public String getPublishingStatus() {
    return publishingStatus;
  }

  public void setPublishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
  }

  public V10VmOpenApiService modified(@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Date when item was modified/created (UTC).
   * @return modified
  **/
  @ApiModelProperty(value = "Date when item was modified/created (UTC).")
  public @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified) {
    this.modified = modified;
  }

  public V10VmOpenApiService responsibleSoteOrganization(String responsibleSoteOrganization) {
    this.responsibleSoteOrganization = responsibleSoteOrganization;
    return this;
  }

   /**
   * Sote organization that is responsible for the service. Notice! At the moment always empty - the property is a placeholder for later use.
   * @return responsibleSoteOrganization
  **/
  @ApiModelProperty(value = "Sote organization that is responsible for the service. Notice! At the moment always empty - the property is a placeholder for later use.")
  public String getResponsibleSoteOrganization() {
    return responsibleSoteOrganization;
  }

  public void setResponsibleSoteOrganization(String responsibleSoteOrganization) {
    this.responsibleSoteOrganization = responsibleSoteOrganization;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V10VmOpenApiService v10VmOpenApiService = (V10VmOpenApiService) o;
    return Objects.equals(this.id, v10VmOpenApiService.id) &&
        Objects.equals(this.sourceId, v10VmOpenApiService.sourceId) &&
        Objects.equals(this.generalDescriptionId, v10VmOpenApiService.generalDescriptionId) &&
        Objects.equals(this.subType, v10VmOpenApiService.subType) &&
        Objects.equals(this.type, v10VmOpenApiService.type) &&
        Objects.equals(this.fundingType, v10VmOpenApiService.fundingType) &&
        Objects.equals(this.serviceNames, v10VmOpenApiService.serviceNames) &&
        Objects.equals(this.serviceChargeType, v10VmOpenApiService.serviceChargeType) &&
        Objects.equals(this.areaType, v10VmOpenApiService.areaType) &&
        Objects.equals(this.areas, v10VmOpenApiService.areas) &&
        Objects.equals(this.serviceDescriptions, v10VmOpenApiService.serviceDescriptions) &&
        Objects.equals(this.languages, v10VmOpenApiService.languages) &&
        Objects.equals(this.serviceClasses, v10VmOpenApiService.serviceClasses) &&
        Objects.equals(this.ontologyTerms, v10VmOpenApiService.ontologyTerms) &&
        Objects.equals(this.targetGroups, v10VmOpenApiService.targetGroups) &&
        Objects.equals(this.lifeEvents, v10VmOpenApiService.lifeEvents) &&
        Objects.equals(this.industrialClasses, v10VmOpenApiService.industrialClasses) &&
        Objects.equals(this.legislation, v10VmOpenApiService.legislation) &&
        Objects.equals(this.keywords, v10VmOpenApiService.keywords) &&
        Objects.equals(this.requirements, v10VmOpenApiService.requirements) &&
        Objects.equals(this.serviceChannels, v10VmOpenApiService.serviceChannels) &&
        Objects.equals(this.organizations, v10VmOpenApiService.organizations) &&
        Objects.equals(this.serviceVouchersInUse, v10VmOpenApiService.serviceVouchersInUse) &&
        Objects.equals(this.serviceVouchers, v10VmOpenApiService.serviceVouchers) &&
        Objects.equals(this.serviceCollections, v10VmOpenApiService.serviceCollections) &&
        Objects.equals(this.publishingStatus, v10VmOpenApiService.publishingStatus) &&
        Objects.equals(this.modified, v10VmOpenApiService.modified) &&
        Objects.equals(this.responsibleSoteOrganization, v10VmOpenApiService.responsibleSoteOrganization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceId, generalDescriptionId, subType, type, fundingType, serviceNames, serviceChargeType, areaType, areas, serviceDescriptions, languages, serviceClasses, ontologyTerms, targetGroups, lifeEvents, industrialClasses, legislation, keywords, requirements, serviceChannels, organizations, serviceVouchersInUse, serviceVouchers, serviceCollections, publishingStatus, modified, responsibleSoteOrganization);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V10VmOpenApiService {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    generalDescriptionId: ").append(toIndentedString(generalDescriptionId)).append("\n");
    sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    fundingType: ").append(toIndentedString(fundingType)).append("\n");
    sb.append("    serviceNames: ").append(toIndentedString(serviceNames)).append("\n");
    sb.append("    serviceChargeType: ").append(toIndentedString(serviceChargeType)).append("\n");
    sb.append("    areaType: ").append(toIndentedString(areaType)).append("\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("    serviceDescriptions: ").append(toIndentedString(serviceDescriptions)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    serviceClasses: ").append(toIndentedString(serviceClasses)).append("\n");
    sb.append("    ontologyTerms: ").append(toIndentedString(ontologyTerms)).append("\n");
    sb.append("    targetGroups: ").append(toIndentedString(targetGroups)).append("\n");
    sb.append("    lifeEvents: ").append(toIndentedString(lifeEvents)).append("\n");
    sb.append("    industrialClasses: ").append(toIndentedString(industrialClasses)).append("\n");
    sb.append("    legislation: ").append(toIndentedString(legislation)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("    serviceChannels: ").append(toIndentedString(serviceChannels)).append("\n");
    sb.append("    organizations: ").append(toIndentedString(organizations)).append("\n");
    sb.append("    serviceVouchersInUse: ").append(toIndentedString(serviceVouchersInUse)).append("\n");
    sb.append("    serviceVouchers: ").append(toIndentedString(serviceVouchers)).append("\n");
    sb.append("    serviceCollections: ").append(toIndentedString(serviceCollections)).append("\n");
    sb.append("    publishingStatus: ").append(toIndentedString(publishingStatus)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    responsibleSoteOrganization: ").append(toIndentedString(responsibleSoteOrganization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

