/*
 * PTV Open Api version 10
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.ptv.client.model.V10VmOpenApiServiceChannelService;
import fi.metatavu.ptv.client.model.V4VmOpenApiFintoItem;
import fi.metatavu.ptv.client.model.V4VmOpenApiPhone;
import fi.metatavu.ptv.client.model.V8VmOpenApiServiceHour;
import fi.metatavu.ptv.client.model.V9VmOpenApiWebPage;
import fi.metatavu.ptv.client.model.VmOpenApiAccessibilityClassification;
import fi.metatavu.ptv.client.model.VmOpenApiArea;
import fi.metatavu.ptv.client.model.VmOpenApiAttachmentWithType;
import fi.metatavu.ptv.client.model.VmOpenApiLanguageItem;
import fi.metatavu.ptv.client.model.VmOpenApiLocalizedListItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * OPEN API V10 - View Model of electronic channel
 */
@ApiModel(description = "OPEN API V10 - View Model of electronic channel")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-08T12:51:13.642+03:00")
public class V10VmOpenApiElectronicChannel {
  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("sourceId")
  private String sourceId = null;

  @JsonProperty("serviceChannelType")
  private String serviceChannelType = null;

  @JsonProperty("organizationId")
  private UUID organizationId = null;

  @JsonProperty("serviceChannelNames")
  private List<VmOpenApiLocalizedListItem> serviceChannelNames = null;

  @JsonProperty("serviceChannelDescriptions")
  private List<VmOpenApiLocalizedListItem> serviceChannelDescriptions = null;

  @JsonProperty("areaType")
  private String areaType = null;

  @JsonProperty("areas")
  private List<VmOpenApiArea> areas = null;

  @JsonProperty("signatureQuantity")
  private Integer signatureQuantity = null;

  @JsonProperty("requiresSignature")
  private Boolean requiresSignature = null;

  @JsonProperty("requiresAuthentication")
  private Boolean requiresAuthentication = null;

  @JsonProperty("attachments")
  private List<VmOpenApiAttachmentWithType> attachments = null;

  @JsonProperty("supportPhones")
  private List<V4VmOpenApiPhone> supportPhones = null;

  @JsonProperty("supportEmails")
  private List<VmOpenApiLanguageItem> supportEmails = null;

  @JsonProperty("languages")
  private List<String> languages = null;

  @JsonProperty("webPages")
  private List<V9VmOpenApiWebPage> webPages = null;

  @JsonProperty("serviceHours")
  private List<V8VmOpenApiServiceHour> serviceHours = null;

  @JsonProperty("accessibilityClassification")
  private List<VmOpenApiAccessibilityClassification> accessibilityClassification = null;

  @JsonProperty("services")
  private List<V10VmOpenApiServiceChannelService> services = null;

  @JsonProperty("publishingStatus")
  private String publishingStatus = null;

  @JsonProperty("modified")
  private @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified = null;

  @JsonProperty("responsibleSoteOrganization")
  private String responsibleSoteOrganization = null;

  @JsonProperty("ontologyTerms")
  private List<V4VmOpenApiFintoItem> ontologyTerms = null;

  public V10VmOpenApiElectronicChannel id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * PTV identifier for the service channel.
   * @return id
  **/
  @ApiModelProperty(value = "PTV identifier for the service channel.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public V10VmOpenApiElectronicChannel sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * External system identifier for this service channel. User needs to be logged in to be able to get/set value.
   * @return sourceId
  **/
  @ApiModelProperty(value = "External system identifier for this service channel. User needs to be logged in to be able to get/set value.")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public V10VmOpenApiElectronicChannel serviceChannelType(String serviceChannelType) {
    this.serviceChannelType = serviceChannelType;
    return this;
  }

   /**
   * Type of the service channel. Channel types: EChannel, WebPage, PrintableForm, Phone or ServiceLocation.
   * @return serviceChannelType
  **/
  @ApiModelProperty(value = "Type of the service channel. Channel types: EChannel, WebPage, PrintableForm, Phone or ServiceLocation.")
  public String getServiceChannelType() {
    return serviceChannelType;
  }

  public void setServiceChannelType(String serviceChannelType) {
    this.serviceChannelType = serviceChannelType;
  }

  public V10VmOpenApiElectronicChannel organizationId(UUID organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * PTV organization identifier responsible for the channel.
   * @return organizationId
  **/
  @ApiModelProperty(value = "PTV organization identifier responsible for the channel.")
  public UUID getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(UUID organizationId) {
    this.organizationId = organizationId;
  }

  public V10VmOpenApiElectronicChannel serviceChannelNames(List<VmOpenApiLocalizedListItem> serviceChannelNames) {
    this.serviceChannelNames = serviceChannelNames;
    return this;
  }

  public V10VmOpenApiElectronicChannel addServiceChannelNamesItem(VmOpenApiLocalizedListItem serviceChannelNamesItem) {
    if (this.serviceChannelNames == null) {
      this.serviceChannelNames = new ArrayList<VmOpenApiLocalizedListItem>();
    }
    this.serviceChannelNames.add(serviceChannelNamesItem);
    return this;
  }

   /**
   * Localized list of service channel names. Possible type values are: Name, AlternativeName (in version 7 AlternateName).
   * @return serviceChannelNames
  **/
  @ApiModelProperty(value = "Localized list of service channel names. Possible type values are: Name, AlternativeName (in version 7 AlternateName).")
  public List<VmOpenApiLocalizedListItem> getServiceChannelNames() {
    return serviceChannelNames;
  }

  public void setServiceChannelNames(List<VmOpenApiLocalizedListItem> serviceChannelNames) {
    this.serviceChannelNames = serviceChannelNames;
  }

  public V10VmOpenApiElectronicChannel serviceChannelDescriptions(List<VmOpenApiLocalizedListItem> serviceChannelDescriptions) {
    this.serviceChannelDescriptions = serviceChannelDescriptions;
    return this;
  }

  public V10VmOpenApiElectronicChannel addServiceChannelDescriptionsItem(VmOpenApiLocalizedListItem serviceChannelDescriptionsItem) {
    if (this.serviceChannelDescriptions == null) {
      this.serviceChannelDescriptions = new ArrayList<VmOpenApiLocalizedListItem>();
    }
    this.serviceChannelDescriptions.add(serviceChannelDescriptionsItem);
    return this;
  }

   /**
   * List of localized service channel descriptions. Possible type values are: Description, Summary (in version 7 ShortDescription).
   * @return serviceChannelDescriptions
  **/
  @ApiModelProperty(value = "List of localized service channel descriptions. Possible type values are: Description, Summary (in version 7 ShortDescription).")
  public List<VmOpenApiLocalizedListItem> getServiceChannelDescriptions() {
    return serviceChannelDescriptions;
  }

  public void setServiceChannelDescriptions(List<VmOpenApiLocalizedListItem> serviceChannelDescriptions) {
    this.serviceChannelDescriptions = serviceChannelDescriptions;
  }

  public V10VmOpenApiElectronicChannel areaType(String areaType) {
    this.areaType = areaType;
    return this;
  }

   /**
   * Area type. Possible values are: Nationwide, NationwideExceptAlandIslands or LimitedType.  In version 7 and older: WholeCountry, WholeCountryExceptAlandIslands, AreaType.
   * @return areaType
  **/
  @ApiModelProperty(value = "Area type. Possible values are: Nationwide, NationwideExceptAlandIslands or LimitedType.  In version 7 and older: WholeCountry, WholeCountryExceptAlandIslands, AreaType.")
  public String getAreaType() {
    return areaType;
  }

  public void setAreaType(String areaType) {
    this.areaType = areaType;
  }

  public V10VmOpenApiElectronicChannel areas(List<VmOpenApiArea> areas) {
    this.areas = areas;
    return this;
  }

  public V10VmOpenApiElectronicChannel addAreasItem(VmOpenApiArea areasItem) {
    if (this.areas == null) {
      this.areas = new ArrayList<VmOpenApiArea>();
    }
    this.areas.add(areasItem);
    return this;
  }

   /**
   * List of service channel areas.
   * @return areas
  **/
  @ApiModelProperty(value = "List of service channel areas.")
  public List<VmOpenApiArea> getAreas() {
    return areas;
  }

  public void setAreas(List<VmOpenApiArea> areas) {
    this.areas = areas;
  }

  public V10VmOpenApiElectronicChannel signatureQuantity(Integer signatureQuantity) {
    this.signatureQuantity = signatureQuantity;
    return this;
  }

   /**
   * How many signatures are required.
   * @return signatureQuantity
  **/
  @ApiModelProperty(value = "How many signatures are required.")
  public Integer getSignatureQuantity() {
    return signatureQuantity;
  }

  public void setSignatureQuantity(Integer signatureQuantity) {
    this.signatureQuantity = signatureQuantity;
  }

  public V10VmOpenApiElectronicChannel requiresSignature(Boolean requiresSignature) {
    this.requiresSignature = requiresSignature;
    return this;
  }

   /**
   * Is signature required.
   * @return requiresSignature
  **/
  @ApiModelProperty(value = "Is signature required.")
  public Boolean getRequiresSignature() {
    return requiresSignature;
  }

  public void setRequiresSignature(Boolean requiresSignature) {
    this.requiresSignature = requiresSignature;
  }

  public V10VmOpenApiElectronicChannel requiresAuthentication(Boolean requiresAuthentication) {
    this.requiresAuthentication = requiresAuthentication;
    return this;
  }

   /**
   * Does the electronic channel require authentication.
   * @return requiresAuthentication
  **/
  @ApiModelProperty(value = "Does the electronic channel require authentication.")
  public Boolean getRequiresAuthentication() {
    return requiresAuthentication;
  }

  public void setRequiresAuthentication(Boolean requiresAuthentication) {
    this.requiresAuthentication = requiresAuthentication;
  }

  public V10VmOpenApiElectronicChannel attachments(List<VmOpenApiAttachmentWithType> attachments) {
    this.attachments = attachments;
    return this;
  }

  public V10VmOpenApiElectronicChannel addAttachmentsItem(VmOpenApiAttachmentWithType attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<VmOpenApiAttachmentWithType>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * List of attachments.
   * @return attachments
  **/
  @ApiModelProperty(value = "List of attachments.")
  public List<VmOpenApiAttachmentWithType> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<VmOpenApiAttachmentWithType> attachments) {
    this.attachments = attachments;
  }

  public V10VmOpenApiElectronicChannel supportPhones(List<V4VmOpenApiPhone> supportPhones) {
    this.supportPhones = supportPhones;
    return this;
  }

  public V10VmOpenApiElectronicChannel addSupportPhonesItem(V4VmOpenApiPhone supportPhonesItem) {
    if (this.supportPhones == null) {
      this.supportPhones = new ArrayList<V4VmOpenApiPhone>();
    }
    this.supportPhones.add(supportPhonesItem);
    return this;
  }

   /**
   * List of support phone numbers for the service channel.
   * @return supportPhones
  **/
  @ApiModelProperty(value = "List of support phone numbers for the service channel.")
  public List<V4VmOpenApiPhone> getSupportPhones() {
    return supportPhones;
  }

  public void setSupportPhones(List<V4VmOpenApiPhone> supportPhones) {
    this.supportPhones = supportPhones;
  }

  public V10VmOpenApiElectronicChannel supportEmails(List<VmOpenApiLanguageItem> supportEmails) {
    this.supportEmails = supportEmails;
    return this;
  }

  public V10VmOpenApiElectronicChannel addSupportEmailsItem(VmOpenApiLanguageItem supportEmailsItem) {
    if (this.supportEmails == null) {
      this.supportEmails = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.supportEmails.add(supportEmailsItem);
    return this;
  }

   /**
   * List of support email addresses for the service channel.
   * @return supportEmails
  **/
  @ApiModelProperty(value = "List of support email addresses for the service channel.")
  public List<VmOpenApiLanguageItem> getSupportEmails() {
    return supportEmails;
  }

  public void setSupportEmails(List<VmOpenApiLanguageItem> supportEmails) {
    this.supportEmails = supportEmails;
  }

  public V10VmOpenApiElectronicChannel languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public V10VmOpenApiElectronicChannel addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<String>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * List of languages the service channel is available in (two letter language code).
   * @return languages
  **/
  @ApiModelProperty(value = "List of languages the service channel is available in (two letter language code).")
  public List<String> getLanguages() {
    return languages;
  }

  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }

  public V10VmOpenApiElectronicChannel webPages(List<V9VmOpenApiWebPage> webPages) {
    this.webPages = webPages;
    return this;
  }

  public V10VmOpenApiElectronicChannel addWebPagesItem(V9VmOpenApiWebPage webPagesItem) {
    if (this.webPages == null) {
      this.webPages = new ArrayList<V9VmOpenApiWebPage>();
    }
    this.webPages.add(webPagesItem);
    return this;
  }

   /**
   * List of service channel web pages.
   * @return webPages
  **/
  @ApiModelProperty(value = "List of service channel web pages.")
  public List<V9VmOpenApiWebPage> getWebPages() {
    return webPages;
  }

  public void setWebPages(List<V9VmOpenApiWebPage> webPages) {
    this.webPages = webPages;
  }

  public V10VmOpenApiElectronicChannel serviceHours(List<V8VmOpenApiServiceHour> serviceHours) {
    this.serviceHours = serviceHours;
    return this;
  }

  public V10VmOpenApiElectronicChannel addServiceHoursItem(V8VmOpenApiServiceHour serviceHoursItem) {
    if (this.serviceHours == null) {
      this.serviceHours = new ArrayList<V8VmOpenApiServiceHour>();
    }
    this.serviceHours.add(serviceHoursItem);
    return this;
  }

   /**
   * List of service channel service hours.
   * @return serviceHours
  **/
  @ApiModelProperty(value = "List of service channel service hours.")
  public List<V8VmOpenApiServiceHour> getServiceHours() {
    return serviceHours;
  }

  public void setServiceHours(List<V8VmOpenApiServiceHour> serviceHours) {
    this.serviceHours = serviceHours;
  }

  public V10VmOpenApiElectronicChannel accessibilityClassification(List<VmOpenApiAccessibilityClassification> accessibilityClassification) {
    this.accessibilityClassification = accessibilityClassification;
    return this;
  }

  public V10VmOpenApiElectronicChannel addAccessibilityClassificationItem(VmOpenApiAccessibilityClassification accessibilityClassificationItem) {
    if (this.accessibilityClassification == null) {
      this.accessibilityClassification = new ArrayList<VmOpenApiAccessibilityClassification>();
    }
    this.accessibilityClassification.add(accessibilityClassificationItem);
    return this;
  }

   /**
   * The accessibility classification.
   * @return accessibilityClassification
  **/
  @ApiModelProperty(value = "The accessibility classification.")
  public List<VmOpenApiAccessibilityClassification> getAccessibilityClassification() {
    return accessibilityClassification;
  }

  public void setAccessibilityClassification(List<VmOpenApiAccessibilityClassification> accessibilityClassification) {
    this.accessibilityClassification = accessibilityClassification;
  }

  public V10VmOpenApiElectronicChannel services(List<V10VmOpenApiServiceChannelService> services) {
    this.services = services;
    return this;
  }

  public V10VmOpenApiElectronicChannel addServicesItem(V10VmOpenApiServiceChannelService servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<V10VmOpenApiServiceChannelService>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * List of linked services including relationship data.
   * @return services
  **/
  @ApiModelProperty(value = "List of linked services including relationship data.")
  public List<V10VmOpenApiServiceChannelService> getServices() {
    return services;
  }

  public void setServices(List<V10VmOpenApiServiceChannelService> services) {
    this.services = services;
  }

  public V10VmOpenApiElectronicChannel publishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
    return this;
  }

   /**
   * Publishing status. Possible values are: Draft, Published, Deleted or Modified.
   * @return publishingStatus
  **/
  @ApiModelProperty(value = "Publishing status. Possible values are: Draft, Published, Deleted or Modified.")
  public String getPublishingStatus() {
    return publishingStatus;
  }

  public void setPublishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
  }

  public V10VmOpenApiElectronicChannel modified(@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Date when item was modified/created (UTC).
   * @return modified
  **/
  @ApiModelProperty(value = "Date when item was modified/created (UTC).")
  public @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified) {
    this.modified = modified;
  }

  public V10VmOpenApiElectronicChannel responsibleSoteOrganization(String responsibleSoteOrganization) {
    this.responsibleSoteOrganization = responsibleSoteOrganization;
    return this;
  }

   /**
   * Sote organization that is responsible for the service channel. Notice! At the moment always empty - the property is a placeholder for later use.
   * @return responsibleSoteOrganization
  **/
  @ApiModelProperty(value = "Sote organization that is responsible for the service channel. Notice! At the moment always empty - the property is a placeholder for later use.")
  public String getResponsibleSoteOrganization() {
    return responsibleSoteOrganization;
  }

  public void setResponsibleSoteOrganization(String responsibleSoteOrganization) {
    this.responsibleSoteOrganization = responsibleSoteOrganization;
  }

  public V10VmOpenApiElectronicChannel ontologyTerms(List<V4VmOpenApiFintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
    return this;
  }

  public V10VmOpenApiElectronicChannel addOntologyTermsItem(V4VmOpenApiFintoItem ontologyTermsItem) {
    if (this.ontologyTerms == null) {
      this.ontologyTerms = new ArrayList<V4VmOpenApiFintoItem>();
    }
    this.ontologyTerms.add(ontologyTermsItem);
    return this;
  }

   /**
   * List of ontology terms related to the all service connections.
   * @return ontologyTerms
  **/
  @ApiModelProperty(value = "List of ontology terms related to the all service connections.")
  public List<V4VmOpenApiFintoItem> getOntologyTerms() {
    return ontologyTerms;
  }

  public void setOntologyTerms(List<V4VmOpenApiFintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V10VmOpenApiElectronicChannel v10VmOpenApiElectronicChannel = (V10VmOpenApiElectronicChannel) o;
    return Objects.equals(this.id, v10VmOpenApiElectronicChannel.id) &&
        Objects.equals(this.sourceId, v10VmOpenApiElectronicChannel.sourceId) &&
        Objects.equals(this.serviceChannelType, v10VmOpenApiElectronicChannel.serviceChannelType) &&
        Objects.equals(this.organizationId, v10VmOpenApiElectronicChannel.organizationId) &&
        Objects.equals(this.serviceChannelNames, v10VmOpenApiElectronicChannel.serviceChannelNames) &&
        Objects.equals(this.serviceChannelDescriptions, v10VmOpenApiElectronicChannel.serviceChannelDescriptions) &&
        Objects.equals(this.areaType, v10VmOpenApiElectronicChannel.areaType) &&
        Objects.equals(this.areas, v10VmOpenApiElectronicChannel.areas) &&
        Objects.equals(this.signatureQuantity, v10VmOpenApiElectronicChannel.signatureQuantity) &&
        Objects.equals(this.requiresSignature, v10VmOpenApiElectronicChannel.requiresSignature) &&
        Objects.equals(this.requiresAuthentication, v10VmOpenApiElectronicChannel.requiresAuthentication) &&
        Objects.equals(this.attachments, v10VmOpenApiElectronicChannel.attachments) &&
        Objects.equals(this.supportPhones, v10VmOpenApiElectronicChannel.supportPhones) &&
        Objects.equals(this.supportEmails, v10VmOpenApiElectronicChannel.supportEmails) &&
        Objects.equals(this.languages, v10VmOpenApiElectronicChannel.languages) &&
        Objects.equals(this.webPages, v10VmOpenApiElectronicChannel.webPages) &&
        Objects.equals(this.serviceHours, v10VmOpenApiElectronicChannel.serviceHours) &&
        Objects.equals(this.accessibilityClassification, v10VmOpenApiElectronicChannel.accessibilityClassification) &&
        Objects.equals(this.services, v10VmOpenApiElectronicChannel.services) &&
        Objects.equals(this.publishingStatus, v10VmOpenApiElectronicChannel.publishingStatus) &&
        Objects.equals(this.modified, v10VmOpenApiElectronicChannel.modified) &&
        Objects.equals(this.responsibleSoteOrganization, v10VmOpenApiElectronicChannel.responsibleSoteOrganization) &&
        Objects.equals(this.ontologyTerms, v10VmOpenApiElectronicChannel.ontologyTerms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceId, serviceChannelType, organizationId, serviceChannelNames, serviceChannelDescriptions, areaType, areas, signatureQuantity, requiresSignature, requiresAuthentication, attachments, supportPhones, supportEmails, languages, webPages, serviceHours, accessibilityClassification, services, publishingStatus, modified, responsibleSoteOrganization, ontologyTerms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V10VmOpenApiElectronicChannel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    serviceChannelType: ").append(toIndentedString(serviceChannelType)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    serviceChannelNames: ").append(toIndentedString(serviceChannelNames)).append("\n");
    sb.append("    serviceChannelDescriptions: ").append(toIndentedString(serviceChannelDescriptions)).append("\n");
    sb.append("    areaType: ").append(toIndentedString(areaType)).append("\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("    signatureQuantity: ").append(toIndentedString(signatureQuantity)).append("\n");
    sb.append("    requiresSignature: ").append(toIndentedString(requiresSignature)).append("\n");
    sb.append("    requiresAuthentication: ").append(toIndentedString(requiresAuthentication)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    supportPhones: ").append(toIndentedString(supportPhones)).append("\n");
    sb.append("    supportEmails: ").append(toIndentedString(supportEmails)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    webPages: ").append(toIndentedString(webPages)).append("\n");
    sb.append("    serviceHours: ").append(toIndentedString(serviceHours)).append("\n");
    sb.append("    accessibilityClassification: ").append(toIndentedString(accessibilityClassification)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    publishingStatus: ").append(toIndentedString(publishingStatus)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    responsibleSoteOrganization: ").append(toIndentedString(responsibleSoteOrganization)).append("\n");
    sb.append("    ontologyTerms: ").append(toIndentedString(ontologyTerms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

