/**
 * PTV Open Api version 4
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import fi.metatavu.ptv.client.model.VmOpenApiLocalizedListItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * OPEN API V2 - View Model of service and channel relation
 */
@ApiModel(description = "OPEN API V2 - View Model of service and channel relation")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-10T07:12:40.139+03:00")
public class V2VmOpenApiServiceAndChannel   {
  @JsonProperty("serviceId")
  private String serviceId = null;

  @JsonProperty("serviceChannelId")
  private String serviceChannelId = null;

  @JsonProperty("description")
  private List<VmOpenApiLocalizedListItem> description = new ArrayList<VmOpenApiLocalizedListItem>();

  @JsonProperty("serviceChargeType")
  private String serviceChargeType = null;

  public V2VmOpenApiServiceAndChannel serviceId(String serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * PTV service channel identifier.
   * @return serviceId
  **/
  @ApiModelProperty(example = "null", required = true, value = "PTV service channel identifier.")
  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public V2VmOpenApiServiceAndChannel serviceChannelId(String serviceChannelId) {
    this.serviceChannelId = serviceChannelId;
    return this;
  }

   /**
   * PTV service channel identifier.
   * @return serviceChannelId
  **/
  @ApiModelProperty(example = "null", required = true, value = "PTV service channel identifier.")
  public String getServiceChannelId() {
    return serviceChannelId;
  }

  public void setServiceChannelId(String serviceChannelId) {
    this.serviceChannelId = serviceChannelId;
  }

  public V2VmOpenApiServiceAndChannel description(List<VmOpenApiLocalizedListItem> description) {
    this.description = description;
    return this;
  }

  public V2VmOpenApiServiceAndChannel addDescriptionItem(VmOpenApiLocalizedListItem descriptionItem) {
    this.description.add(descriptionItem);
    return this;
  }

   /**
   * List of localized service channel relationship descriptions.
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "List of localized service channel relationship descriptions.")
  public List<VmOpenApiLocalizedListItem> getDescription() {
    return description;
  }

  public void setDescription(List<VmOpenApiLocalizedListItem> description) {
    this.description = description;
  }

  public V2VmOpenApiServiceAndChannel serviceChargeType(String serviceChargeType) {
    this.serviceChargeType = serviceChargeType;
    return this;
  }

   /**
   * Service charge type. Possible values are: Charged, Free or Other
   * @return serviceChargeType
  **/
  @ApiModelProperty(example = "null", value = "Service charge type. Possible values are: Charged, Free or Other")
  public String getServiceChargeType() {
    return serviceChargeType;
  }

  public void setServiceChargeType(String serviceChargeType) {
    this.serviceChargeType = serviceChargeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2VmOpenApiServiceAndChannel v2VmOpenApiServiceAndChannel = (V2VmOpenApiServiceAndChannel) o;
    return Objects.equals(this.serviceId, v2VmOpenApiServiceAndChannel.serviceId) &&
        Objects.equals(this.serviceChannelId, v2VmOpenApiServiceAndChannel.serviceChannelId) &&
        Objects.equals(this.description, v2VmOpenApiServiceAndChannel.description) &&
        Objects.equals(this.serviceChargeType, v2VmOpenApiServiceAndChannel.serviceChargeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceId, serviceChannelId, description, serviceChargeType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2VmOpenApiServiceAndChannel {\n");
    
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    serviceChannelId: ").append(toIndentedString(serviceChannelId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    serviceChargeType: ").append(toIndentedString(serviceChargeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

