/*
 * PTV Open Api version 6
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * OPEN API V4 - View Model of email
 */
@ApiModel(description = "OPEN API V4 - View Model of email")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-18T13:10:37.869+03:00")
public class V4VmOpenApiEmail {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("language")
  private String language = null;

  public V4VmOpenApiEmail description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Email address description. (Max.Length: 100).
   * @return description
  **/
  @ApiModelProperty(value = "Email address description. (Max.Length: 100).")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public V4VmOpenApiEmail value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Localized value corresponding to the Language property value. (Max.Length: 100).
   * @return value
  **/
  @ApiModelProperty(required = true, value = "Localized value corresponding to the Language property value. (Max.Length: 100).")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public V4VmOpenApiEmail language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Language code.
   * @return language
  **/
  @ApiModelProperty(required = true, value = "Language code.")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V4VmOpenApiEmail v4VmOpenApiEmail = (V4VmOpenApiEmail) o;
    return Objects.equals(this.description, v4VmOpenApiEmail.description) &&
        Objects.equals(this.value, v4VmOpenApiEmail.value) &&
        Objects.equals(this.language, v4VmOpenApiEmail.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, value, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V4VmOpenApiEmail {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

