/*
 * PTV Open Api version 7
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.ptv.client.model.VmOpenApiAddressPostOfficeBox;
import fi.metatavu.ptv.client.model.VmOpenApiAddressStreetWithCoordinates;
import fi.metatavu.ptv.client.model.VmOpenApiLanguageItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * OPEN API V7 - View Model of address
 */
@ApiModel(description = "OPEN API V7 - View Model of address")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-23T08:36:23.831+03:00")
public class V7VmOpenApiAddress {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("subType")
  private String subType = null;

  @JsonProperty("postOfficeBoxAddress")
  private VmOpenApiAddressPostOfficeBox postOfficeBoxAddress = null;

  @JsonProperty("streetAddress")
  private VmOpenApiAddressStreetWithCoordinates streetAddress = null;

  @JsonProperty("foreignAddress")
  private List<VmOpenApiLanguageItem> foreignAddress = null;

  @JsonProperty("country")
  private String country = null;

  public V7VmOpenApiAddress type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Address type, Visiting or Postal.
   * @return type
  **/
  @ApiModelProperty(value = "Address type, Visiting or Postal.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public V7VmOpenApiAddress subType(String subType) {
    this.subType = subType;
    return this;
  }

   /**
   * Address sub type, Street, PostOfficeBox or Foreign.
   * @return subType
  **/
  @ApiModelProperty(value = "Address sub type, Street, PostOfficeBox or Foreign.")
  public String getSubType() {
    return subType;
  }

  public void setSubType(String subType) {
    this.subType = subType;
  }

  public V7VmOpenApiAddress postOfficeBoxAddress(VmOpenApiAddressPostOfficeBox postOfficeBoxAddress) {
    this.postOfficeBoxAddress = postOfficeBoxAddress;
    return this;
  }

   /**
   * Post office box address
   * @return postOfficeBoxAddress
  **/
  @ApiModelProperty(value = "Post office box address")
  public VmOpenApiAddressPostOfficeBox getPostOfficeBoxAddress() {
    return postOfficeBoxAddress;
  }

  public void setPostOfficeBoxAddress(VmOpenApiAddressPostOfficeBox postOfficeBoxAddress) {
    this.postOfficeBoxAddress = postOfficeBoxAddress;
  }

  public V7VmOpenApiAddress streetAddress(VmOpenApiAddressStreetWithCoordinates streetAddress) {
    this.streetAddress = streetAddress;
    return this;
  }

   /**
   * Street address.
   * @return streetAddress
  **/
  @ApiModelProperty(value = "Street address.")
  public VmOpenApiAddressStreetWithCoordinates getStreetAddress() {
    return streetAddress;
  }

  public void setStreetAddress(VmOpenApiAddressStreetWithCoordinates streetAddress) {
    this.streetAddress = streetAddress;
  }

  public V7VmOpenApiAddress foreignAddress(List<VmOpenApiLanguageItem> foreignAddress) {
    this.foreignAddress = foreignAddress;
    return this;
  }

  public V7VmOpenApiAddress addForeignAddressItem(VmOpenApiLanguageItem foreignAddressItem) {
    if (this.foreignAddress == null) {
      this.foreignAddress = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.foreignAddress.add(foreignAddressItem);
    return this;
  }

   /**
   * Localized list of foreign address information.
   * @return foreignAddress
  **/
  @ApiModelProperty(value = "Localized list of foreign address information.")
  public List<VmOpenApiLanguageItem> getForeignAddress() {
    return foreignAddress;
  }

  public void setForeignAddress(List<VmOpenApiLanguageItem> foreignAddress) {
    this.foreignAddress = foreignAddress;
  }

  public V7VmOpenApiAddress country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country code (ISO 3166-1 alpha-2), for example FI.
   * @return country
  **/
  @ApiModelProperty(value = "Country code (ISO 3166-1 alpha-2), for example FI.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V7VmOpenApiAddress v7VmOpenApiAddress = (V7VmOpenApiAddress) o;
    return Objects.equals(this.type, v7VmOpenApiAddress.type) &&
        Objects.equals(this.subType, v7VmOpenApiAddress.subType) &&
        Objects.equals(this.postOfficeBoxAddress, v7VmOpenApiAddress.postOfficeBoxAddress) &&
        Objects.equals(this.streetAddress, v7VmOpenApiAddress.streetAddress) &&
        Objects.equals(this.foreignAddress, v7VmOpenApiAddress.foreignAddress) &&
        Objects.equals(this.country, v7VmOpenApiAddress.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, subType, postOfficeBoxAddress, streetAddress, foreignAddress, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V7VmOpenApiAddress {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
    sb.append("    postOfficeBoxAddress: ").append(toIndentedString(postOfficeBoxAddress)).append("\n");
    sb.append("    streetAddress: ").append(toIndentedString(streetAddress)).append("\n");
    sb.append("    foreignAddress: ").append(toIndentedString(foreignAddress)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

