/*
 * PTV Open Api version 8
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.ptv.client.model.V4VmOpenApiPhone;
import fi.metatavu.ptv.client.model.V7VmOpenApiAddressContactIn;
import fi.metatavu.ptv.client.model.VmOpenApiLanguageItem;
import fi.metatavu.ptv.client.model.VmOpenApiWebPageWithOrderNumber;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * OPEN API - View Model of contact details (PUT) - base version
 */
@ApiModel(description = "OPEN API - View Model of contact details (PUT) - base version")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T13:25:17.639+03:00")
public class V8VmOpenApiContactDetailsInBase {
  @JsonProperty("emails")
  private List<VmOpenApiLanguageItem> emails = null;

  @JsonProperty("phoneNumbers")
  private List<V4VmOpenApiPhone> phoneNumbers = null;

  @JsonProperty("webPages")
  private List<VmOpenApiWebPageWithOrderNumber> webPages = null;

  @JsonProperty("addresses")
  private List<V7VmOpenApiAddressContactIn> addresses = null;

  @JsonProperty("deleteAllEmails")
  private Boolean deleteAllEmails = null;

  @JsonProperty("deleteAllPhones")
  private Boolean deleteAllPhones = null;

  @JsonProperty("deleteAllWebPages")
  private Boolean deleteAllWebPages = null;

  @JsonProperty("deleteAllAddresses")
  private Boolean deleteAllAddresses = null;

  public V8VmOpenApiContactDetailsInBase emails(List<VmOpenApiLanguageItem> emails) {
    this.emails = emails;
    return this;
  }

  public V8VmOpenApiContactDetailsInBase addEmailsItem(VmOpenApiLanguageItem emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * List of connection related email addresses.
   * @return emails
  **/
  @ApiModelProperty(value = "List of connection related email addresses.")
  public List<VmOpenApiLanguageItem> getEmails() {
    return emails;
  }

  public void setEmails(List<VmOpenApiLanguageItem> emails) {
    this.emails = emails;
  }

  public V8VmOpenApiContactDetailsInBase phoneNumbers(List<V4VmOpenApiPhone> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public V8VmOpenApiContactDetailsInBase addPhoneNumbersItem(V4VmOpenApiPhone phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<V4VmOpenApiPhone>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

   /**
   * List of connection related phone numbers.
   * @return phoneNumbers
  **/
  @ApiModelProperty(value = "List of connection related phone numbers.")
  public List<V4VmOpenApiPhone> getPhoneNumbers() {
    return phoneNumbers;
  }

  public void setPhoneNumbers(List<V4VmOpenApiPhone> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }

  public V8VmOpenApiContactDetailsInBase webPages(List<VmOpenApiWebPageWithOrderNumber> webPages) {
    this.webPages = webPages;
    return this;
  }

  public V8VmOpenApiContactDetailsInBase addWebPagesItem(VmOpenApiWebPageWithOrderNumber webPagesItem) {
    if (this.webPages == null) {
      this.webPages = new ArrayList<VmOpenApiWebPageWithOrderNumber>();
    }
    this.webPages.add(webPagesItem);
    return this;
  }

   /**
   * List of connection related web pages.
   * @return webPages
  **/
  @ApiModelProperty(value = "List of connection related web pages.")
  public List<VmOpenApiWebPageWithOrderNumber> getWebPages() {
    return webPages;
  }

  public void setWebPages(List<VmOpenApiWebPageWithOrderNumber> webPages) {
    this.webPages = webPages;
  }

  public V8VmOpenApiContactDetailsInBase addresses(List<V7VmOpenApiAddressContactIn> addresses) {
    this.addresses = addresses;
    return this;
  }

  public V8VmOpenApiContactDetailsInBase addAddressesItem(V7VmOpenApiAddressContactIn addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<V7VmOpenApiAddressContactIn>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * List of service location addresses.
   * @return addresses
  **/
  @ApiModelProperty(value = "List of service location addresses.")
  public List<V7VmOpenApiAddressContactIn> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<V7VmOpenApiAddressContactIn> addresses) {
    this.addresses = addresses;
  }

  public V8VmOpenApiContactDetailsInBase deleteAllEmails(Boolean deleteAllEmails) {
    this.deleteAllEmails = deleteAllEmails;
    return this;
  }

   /**
   * Gets or sets a value indicating whether all emails should be delted.
   * @return deleteAllEmails
  **/
  @ApiModelProperty(value = "Gets or sets a value indicating whether all emails should be delted.")
  public Boolean getDeleteAllEmails() {
    return deleteAllEmails;
  }

  public void setDeleteAllEmails(Boolean deleteAllEmails) {
    this.deleteAllEmails = deleteAllEmails;
  }

  public V8VmOpenApiContactDetailsInBase deleteAllPhones(Boolean deleteAllPhones) {
    this.deleteAllPhones = deleteAllPhones;
    return this;
  }

   /**
   * Gets or sets a value indicating whether all phones should be delted.
   * @return deleteAllPhones
  **/
  @ApiModelProperty(value = "Gets or sets a value indicating whether all phones should be delted.")
  public Boolean getDeleteAllPhones() {
    return deleteAllPhones;
  }

  public void setDeleteAllPhones(Boolean deleteAllPhones) {
    this.deleteAllPhones = deleteAllPhones;
  }

  public V8VmOpenApiContactDetailsInBase deleteAllWebPages(Boolean deleteAllWebPages) {
    this.deleteAllWebPages = deleteAllWebPages;
    return this;
  }

   /**
   * Gets or sets a value indicating whether all web pages should be delted.
   * @return deleteAllWebPages
  **/
  @ApiModelProperty(value = "Gets or sets a value indicating whether all web pages should be delted.")
  public Boolean getDeleteAllWebPages() {
    return deleteAllWebPages;
  }

  public void setDeleteAllWebPages(Boolean deleteAllWebPages) {
    this.deleteAllWebPages = deleteAllWebPages;
  }

  public V8VmOpenApiContactDetailsInBase deleteAllAddresses(Boolean deleteAllAddresses) {
    this.deleteAllAddresses = deleteAllAddresses;
    return this;
  }

   /**
   * Gets or sets a value indicating whether all addresses should be delted.
   * @return deleteAllAddresses
  **/
  @ApiModelProperty(value = "Gets or sets a value indicating whether all addresses should be delted.")
  public Boolean getDeleteAllAddresses() {
    return deleteAllAddresses;
  }

  public void setDeleteAllAddresses(Boolean deleteAllAddresses) {
    this.deleteAllAddresses = deleteAllAddresses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V8VmOpenApiContactDetailsInBase v8VmOpenApiContactDetailsInBase = (V8VmOpenApiContactDetailsInBase) o;
    return Objects.equals(this.emails, v8VmOpenApiContactDetailsInBase.emails) &&
        Objects.equals(this.phoneNumbers, v8VmOpenApiContactDetailsInBase.phoneNumbers) &&
        Objects.equals(this.webPages, v8VmOpenApiContactDetailsInBase.webPages) &&
        Objects.equals(this.addresses, v8VmOpenApiContactDetailsInBase.addresses) &&
        Objects.equals(this.deleteAllEmails, v8VmOpenApiContactDetailsInBase.deleteAllEmails) &&
        Objects.equals(this.deleteAllPhones, v8VmOpenApiContactDetailsInBase.deleteAllPhones) &&
        Objects.equals(this.deleteAllWebPages, v8VmOpenApiContactDetailsInBase.deleteAllWebPages) &&
        Objects.equals(this.deleteAllAddresses, v8VmOpenApiContactDetailsInBase.deleteAllAddresses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emails, phoneNumbers, webPages, addresses, deleteAllEmails, deleteAllPhones, deleteAllWebPages, deleteAllAddresses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V8VmOpenApiContactDetailsInBase {\n");
    
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    webPages: ").append(toIndentedString(webPages)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    deleteAllEmails: ").append(toIndentedString(deleteAllEmails)).append("\n");
    sb.append("    deleteAllPhones: ").append(toIndentedString(deleteAllPhones)).append("\n");
    sb.append("    deleteAllWebPages: ").append(toIndentedString(deleteAllWebPages)).append("\n");
    sb.append("    deleteAllAddresses: ").append(toIndentedString(deleteAllAddresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

