/*
 * PTV Open Api version 8
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.ptv.client.model.V4VmOpenApiPhone;
import fi.metatavu.ptv.client.model.VmOpenApiLanguageItem;
import fi.metatavu.ptv.client.model.VmOpenApiLocalizedListItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * OPEN API V8 - View Model of web page channel for IN api - base
 */
@ApiModel(description = "OPEN API V8 - View Model of web page channel for IN api - base")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T13:25:17.639+03:00")
public class V8VmOpenApiWebPageChannelInBase {
  @JsonProperty("sourceId")
  private String sourceId = null;

  @JsonProperty("serviceChannelDescriptions")
  private List<VmOpenApiLocalizedListItem> serviceChannelDescriptions = null;

  @JsonProperty("organizationId")
  private String organizationId = null;

  @JsonProperty("serviceChannelNames")
  private List<VmOpenApiLanguageItem> serviceChannelNames = null;

  @JsonProperty("webPage")
  private List<VmOpenApiLanguageItem> webPage = null;

  @JsonProperty("supportPhones")
  private List<V4VmOpenApiPhone> supportPhones = null;

  @JsonProperty("supportEmails")
  private List<VmOpenApiLanguageItem> supportEmails = null;

  @JsonProperty("languages")
  private List<String> languages = null;

  @JsonProperty("publishingStatus")
  private String publishingStatus = null;

  @JsonProperty("isVisibleForAll")
  private Boolean isVisibleForAll = null;

  @JsonProperty("deleteAllSupportEmails")
  private Boolean deleteAllSupportEmails = null;

  @JsonProperty("deleteAllSupportPhones")
  private Boolean deleteAllSupportPhones = null;

  public V8VmOpenApiWebPageChannelInBase sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * External system identifier for this service channel. User needs to be logged in to be able to get/set value.
   * @return sourceId
  **/
  @ApiModelProperty(value = "External system identifier for this service channel. User needs to be logged in to be able to get/set value.")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public V8VmOpenApiWebPageChannelInBase serviceChannelDescriptions(List<VmOpenApiLocalizedListItem> serviceChannelDescriptions) {
    this.serviceChannelDescriptions = serviceChannelDescriptions;
    return this;
  }

  public V8VmOpenApiWebPageChannelInBase addServiceChannelDescriptionsItem(VmOpenApiLocalizedListItem serviceChannelDescriptionsItem) {
    if (this.serviceChannelDescriptions == null) {
      this.serviceChannelDescriptions = new ArrayList<VmOpenApiLocalizedListItem>();
    }
    this.serviceChannelDescriptions.add(serviceChannelDescriptionsItem);
    return this;
  }

   /**
   * List of localized service channel descriptions. (Max.Length: 150 Summary).
   * @return serviceChannelDescriptions
  **/
  @ApiModelProperty(value = "List of localized service channel descriptions. (Max.Length: 150 Summary).")
  public List<VmOpenApiLocalizedListItem> getServiceChannelDescriptions() {
    return serviceChannelDescriptions;
  }

  public void setServiceChannelDescriptions(List<VmOpenApiLocalizedListItem> serviceChannelDescriptions) {
    this.serviceChannelDescriptions = serviceChannelDescriptions;
  }

  public V8VmOpenApiWebPageChannelInBase organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * PTV organization identifier for organization responsible for this service channel.
   * @return organizationId
  **/
  @ApiModelProperty(value = "PTV organization identifier for organization responsible for this service channel.")
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public V8VmOpenApiWebPageChannelInBase serviceChannelNames(List<VmOpenApiLanguageItem> serviceChannelNames) {
    this.serviceChannelNames = serviceChannelNames;
    return this;
  }

  public V8VmOpenApiWebPageChannelInBase addServiceChannelNamesItem(VmOpenApiLanguageItem serviceChannelNamesItem) {
    if (this.serviceChannelNames == null) {
      this.serviceChannelNames = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.serviceChannelNames.add(serviceChannelNamesItem);
    return this;
  }

   /**
   * Localized list of service channel names. (Max.Length: 100).
   * @return serviceChannelNames
  **/
  @ApiModelProperty(value = "Localized list of service channel names. (Max.Length: 100).")
  public List<VmOpenApiLanguageItem> getServiceChannelNames() {
    return serviceChannelNames;
  }

  public void setServiceChannelNames(List<VmOpenApiLanguageItem> serviceChannelNames) {
    this.serviceChannelNames = serviceChannelNames;
  }

  public V8VmOpenApiWebPageChannelInBase webPage(List<VmOpenApiLanguageItem> webPage) {
    this.webPage = webPage;
    return this;
  }

  public V8VmOpenApiWebPageChannelInBase addWebPageItem(VmOpenApiLanguageItem webPageItem) {
    if (this.webPage == null) {
      this.webPage = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.webPage.add(webPageItem);
    return this;
  }

   /**
   * List of localized urls. (Max.Length: 500).
   * @return webPage
  **/
  @ApiModelProperty(value = "List of localized urls. (Max.Length: 500).")
  public List<VmOpenApiLanguageItem> getWebPage() {
    return webPage;
  }

  public void setWebPage(List<VmOpenApiLanguageItem> webPage) {
    this.webPage = webPage;
  }

  public V8VmOpenApiWebPageChannelInBase supportPhones(List<V4VmOpenApiPhone> supportPhones) {
    this.supportPhones = supportPhones;
    return this;
  }

  public V8VmOpenApiWebPageChannelInBase addSupportPhonesItem(V4VmOpenApiPhone supportPhonesItem) {
    if (this.supportPhones == null) {
      this.supportPhones = new ArrayList<V4VmOpenApiPhone>();
    }
    this.supportPhones.add(supportPhonesItem);
    return this;
  }

   /**
   * List of support phone numbers for the service channel.
   * @return supportPhones
  **/
  @ApiModelProperty(value = "List of support phone numbers for the service channel.")
  public List<V4VmOpenApiPhone> getSupportPhones() {
    return supportPhones;
  }

  public void setSupportPhones(List<V4VmOpenApiPhone> supportPhones) {
    this.supportPhones = supportPhones;
  }

  public V8VmOpenApiWebPageChannelInBase supportEmails(List<VmOpenApiLanguageItem> supportEmails) {
    this.supportEmails = supportEmails;
    return this;
  }

  public V8VmOpenApiWebPageChannelInBase addSupportEmailsItem(VmOpenApiLanguageItem supportEmailsItem) {
    if (this.supportEmails == null) {
      this.supportEmails = new ArrayList<VmOpenApiLanguageItem>();
    }
    this.supportEmails.add(supportEmailsItem);
    return this;
  }

   /**
   * List of support email addresses for the service channel. (Max.Length: 100).
   * @return supportEmails
  **/
  @ApiModelProperty(value = "List of support email addresses for the service channel. (Max.Length: 100).")
  public List<VmOpenApiLanguageItem> getSupportEmails() {
    return supportEmails;
  }

  public void setSupportEmails(List<VmOpenApiLanguageItem> supportEmails) {
    this.supportEmails = supportEmails;
  }

  public V8VmOpenApiWebPageChannelInBase languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public V8VmOpenApiWebPageChannelInBase addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<String>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * List of languages the service channel is available in (two letter language code).
   * @return languages
  **/
  @ApiModelProperty(value = "List of languages the service channel is available in (two letter language code).")
  public List<String> getLanguages() {
    return languages;
  }

  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }

  public V8VmOpenApiWebPageChannelInBase publishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
    return this;
  }

   /**
   * Service channel publishing status. Values: Draft, Published, Deleted or Modified.
   * @return publishingStatus
  **/
  @ApiModelProperty(required = true, value = "Service channel publishing status. Values: Draft, Published, Deleted or Modified.")
  public String getPublishingStatus() {
    return publishingStatus;
  }

  public void setPublishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
  }

  public V8VmOpenApiWebPageChannelInBase isVisibleForAll(Boolean isVisibleForAll) {
    this.isVisibleForAll = isVisibleForAll;
    return this;
  }

   /**
   * Indicates if channel can be used (referenced within services) by other users from other organizations.
   * @return isVisibleForAll
  **/
  @ApiModelProperty(value = "Indicates if channel can be used (referenced within services) by other users from other organizations.")
  public Boolean getIsVisibleForAll() {
    return isVisibleForAll;
  }

  public void setIsVisibleForAll(Boolean isVisibleForAll) {
    this.isVisibleForAll = isVisibleForAll;
  }

  public V8VmOpenApiWebPageChannelInBase deleteAllSupportEmails(Boolean deleteAllSupportEmails) {
    this.deleteAllSupportEmails = deleteAllSupportEmails;
    return this;
  }

   /**
   * Set to true to delete all existing support email addresses for the service channel. The SupportEmails collection should be empty when this property is set to true.
   * @return deleteAllSupportEmails
  **/
  @ApiModelProperty(value = "Set to true to delete all existing support email addresses for the service channel. The SupportEmails collection should be empty when this property is set to true.")
  public Boolean getDeleteAllSupportEmails() {
    return deleteAllSupportEmails;
  }

  public void setDeleteAllSupportEmails(Boolean deleteAllSupportEmails) {
    this.deleteAllSupportEmails = deleteAllSupportEmails;
  }

  public V8VmOpenApiWebPageChannelInBase deleteAllSupportPhones(Boolean deleteAllSupportPhones) {
    this.deleteAllSupportPhones = deleteAllSupportPhones;
    return this;
  }

   /**
   * Set to true to delete all existing support phone numbers for the service channel. The SupportPhones collection should be empty when this property is set to true.
   * @return deleteAllSupportPhones
  **/
  @ApiModelProperty(value = "Set to true to delete all existing support phone numbers for the service channel. The SupportPhones collection should be empty when this property is set to true.")
  public Boolean getDeleteAllSupportPhones() {
    return deleteAllSupportPhones;
  }

  public void setDeleteAllSupportPhones(Boolean deleteAllSupportPhones) {
    this.deleteAllSupportPhones = deleteAllSupportPhones;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V8VmOpenApiWebPageChannelInBase v8VmOpenApiWebPageChannelInBase = (V8VmOpenApiWebPageChannelInBase) o;
    return Objects.equals(this.sourceId, v8VmOpenApiWebPageChannelInBase.sourceId) &&
        Objects.equals(this.serviceChannelDescriptions, v8VmOpenApiWebPageChannelInBase.serviceChannelDescriptions) &&
        Objects.equals(this.organizationId, v8VmOpenApiWebPageChannelInBase.organizationId) &&
        Objects.equals(this.serviceChannelNames, v8VmOpenApiWebPageChannelInBase.serviceChannelNames) &&
        Objects.equals(this.webPage, v8VmOpenApiWebPageChannelInBase.webPage) &&
        Objects.equals(this.supportPhones, v8VmOpenApiWebPageChannelInBase.supportPhones) &&
        Objects.equals(this.supportEmails, v8VmOpenApiWebPageChannelInBase.supportEmails) &&
        Objects.equals(this.languages, v8VmOpenApiWebPageChannelInBase.languages) &&
        Objects.equals(this.publishingStatus, v8VmOpenApiWebPageChannelInBase.publishingStatus) &&
        Objects.equals(this.isVisibleForAll, v8VmOpenApiWebPageChannelInBase.isVisibleForAll) &&
        Objects.equals(this.deleteAllSupportEmails, v8VmOpenApiWebPageChannelInBase.deleteAllSupportEmails) &&
        Objects.equals(this.deleteAllSupportPhones, v8VmOpenApiWebPageChannelInBase.deleteAllSupportPhones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceId, serviceChannelDescriptions, organizationId, serviceChannelNames, webPage, supportPhones, supportEmails, languages, publishingStatus, isVisibleForAll, deleteAllSupportEmails, deleteAllSupportPhones);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V8VmOpenApiWebPageChannelInBase {\n");
    
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    serviceChannelDescriptions: ").append(toIndentedString(serviceChannelDescriptions)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    serviceChannelNames: ").append(toIndentedString(serviceChannelNames)).append("\n");
    sb.append("    webPage: ").append(toIndentedString(webPage)).append("\n");
    sb.append("    supportPhones: ").append(toIndentedString(supportPhones)).append("\n");
    sb.append("    supportEmails: ").append(toIndentedString(supportEmails)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    publishingStatus: ").append(toIndentedString(publishingStatus)).append("\n");
    sb.append("    isVisibleForAll: ").append(toIndentedString(isVisibleForAll)).append("\n");
    sb.append("    deleteAllSupportEmails: ").append(toIndentedString(deleteAllSupportEmails)).append("\n");
    sb.append("    deleteAllSupportPhones: ").append(toIndentedString(deleteAllSupportPhones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

