/*
 * PTV Open Api version 9
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fi.metatavu.ptv.client.model.V4VmOpenApiEmail;
import fi.metatavu.ptv.client.model.V4VmOpenApiPhone;
import fi.metatavu.ptv.client.model.V5VmOpenApiOrganizationService;
import fi.metatavu.ptv.client.model.V9VmOpenApiAddress;
import fi.metatavu.ptv.client.model.V9VmOpenApiWebPage;
import fi.metatavu.ptv.client.model.VmOpenApiArea;
import fi.metatavu.ptv.client.model.VmOpenApiItem;
import fi.metatavu.ptv.client.model.VmOpenApiLocalizedListItem;
import fi.metatavu.ptv.client.model.VmOpenApiMunicipality;
import fi.metatavu.ptv.client.model.VmOpenApiNameTypeByLanguage;
import fi.metatavu.ptv.client.model.VmOpenApiOrganizationEInvoicing;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * OPEN API V9 - View Model of organization
 */
@ApiModel(description = "OPEN API V9 - View Model of organization")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-05T18:15:03.681+03:00")
public class V9VmOpenApiOrganization {
  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("sourceId")
  private String sourceId = null;

  @JsonProperty("oid")
  private String oid = null;

  @JsonProperty("parentOrganizationId")
  private UUID parentOrganizationId = null;

  @JsonProperty("organizationRootId")
  private UUID organizationRootId = null;

  @JsonProperty("municipality")
  private VmOpenApiMunicipality municipality = null;

  @JsonProperty("organizationType")
  private String organizationType = null;

  @JsonProperty("businessCode")
  private String businessCode = null;

  @JsonProperty("businessName")
  private String businessName = null;

  @JsonProperty("organizationNames")
  private List<VmOpenApiLocalizedListItem> organizationNames = null;

  @JsonProperty("displayNameType")
  private List<VmOpenApiNameTypeByLanguage> displayNameType = null;

  @JsonProperty("areaType")
  private String areaType = null;

  @JsonProperty("areas")
  private List<VmOpenApiArea> areas = null;

  @JsonProperty("organizationDescriptions")
  private List<VmOpenApiLocalizedListItem> organizationDescriptions = null;

  @JsonProperty("emails")
  private List<V4VmOpenApiEmail> emails = null;

  @JsonProperty("phoneNumbers")
  private List<V4VmOpenApiPhone> phoneNumbers = null;

  @JsonProperty("webPages")
  private List<V9VmOpenApiWebPage> webPages = null;

  @JsonProperty("addresses")
  private List<V9VmOpenApiAddress> addresses = null;

  @JsonProperty("electronicInvoicings")
  private List<VmOpenApiOrganizationEInvoicing> electronicInvoicings = null;

  @JsonProperty("publishingStatus")
  private String publishingStatus = null;

  @JsonProperty("services")
  private List<V5VmOpenApiOrganizationService> services = null;

  @JsonProperty("modified")
  private @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified = null;

  @JsonProperty("subOrganizations")
  private List<VmOpenApiItem> subOrganizations = null;

  @JsonProperty("responsibleOrganizationId")
  private UUID responsibleOrganizationId = null;

  public V9VmOpenApiOrganization id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Entity identifier.
   * @return id
  **/
  @ApiModelProperty(value = "Entity identifier.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public V9VmOpenApiOrganization sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Organization external system identifier. User needs to be logged in to be able to get/set value.
   * @return sourceId
  **/
  @ApiModelProperty(value = "Organization external system identifier. User needs to be logged in to be able to get/set value.")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public V9VmOpenApiOrganization oid(String oid) {
    this.oid = oid;
    return this;
  }

   /**
   * Organization OID. - must match the regex @\&quot;^[A-Za-z0-9.-]*$\&quot;
   * @return oid
  **/
  @ApiModelProperty(value = "Organization OID. - must match the regex @\"^[A-Za-z0-9.-]*$\"")
  public String getOid() {
    return oid;
  }

  public void setOid(String oid) {
    this.oid = oid;
  }

  public V9VmOpenApiOrganization parentOrganizationId(UUID parentOrganizationId) {
    this.parentOrganizationId = parentOrganizationId;
    return this;
  }

   /**
   * Organizations parent organization identifier if exists.
   * @return parentOrganizationId
  **/
  @ApiModelProperty(value = "Organizations parent organization identifier if exists.")
  public UUID getParentOrganizationId() {
    return parentOrganizationId;
  }

  public void setParentOrganizationId(UUID parentOrganizationId) {
    this.parentOrganizationId = parentOrganizationId;
  }

  public V9VmOpenApiOrganization organizationRootId(UUID organizationRootId) {
    this.organizationRootId = organizationRootId;
    return this;
  }

   /**
   * Organizations root organization identifier if exists.
   * @return organizationRootId
  **/
  @ApiModelProperty(value = "Organizations root organization identifier if exists.")
  public UUID getOrganizationRootId() {
    return organizationRootId;
  }

  public void setOrganizationRootId(UUID organizationRootId) {
    this.organizationRootId = organizationRootId;
  }

  public V9VmOpenApiOrganization municipality(VmOpenApiMunicipality municipality) {
    this.municipality = municipality;
    return this;
  }

   /**
   * Municipality including municipality code and a localized list of municipality names.
   * @return municipality
  **/
  @ApiModelProperty(value = "Municipality including municipality code and a localized list of municipality names.")
  public VmOpenApiMunicipality getMunicipality() {
    return municipality;
  }

  public void setMunicipality(VmOpenApiMunicipality municipality) {
    this.municipality = municipality;
  }

  public V9VmOpenApiOrganization organizationType(String organizationType) {
    this.organizationType = organizationType;
    return this;
  }

   /**
   * Organization type (State, Municipality, RegionalOrganization, Organization, Company, SotePublic, SotePrivate, Region).
   * @return organizationType
  **/
  @ApiModelProperty(value = "Organization type (State, Municipality, RegionalOrganization, Organization, Company, SotePublic, SotePrivate, Region).")
  public String getOrganizationType() {
    return organizationType;
  }

  public void setOrganizationType(String organizationType) {
    this.organizationType = organizationType;
  }

  public V9VmOpenApiOrganization businessCode(String businessCode) {
    this.businessCode = businessCode;
    return this;
  }

   /**
   * Organization business code (Y-tunnus).
   * @return businessCode
  **/
  @ApiModelProperty(value = "Organization business code (Y-tunnus).")
  public String getBusinessCode() {
    return businessCode;
  }

  public void setBusinessCode(String businessCode) {
    this.businessCode = businessCode;
  }

  public V9VmOpenApiOrganization businessName(String businessName) {
    this.businessName = businessName;
    return this;
  }

   /**
   * Organization business name (name used for business code).
   * @return businessName
  **/
  @ApiModelProperty(value = "Organization business name (name used for business code).")
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(String businessName) {
    this.businessName = businessName;
  }

  public V9VmOpenApiOrganization organizationNames(List<VmOpenApiLocalizedListItem> organizationNames) {
    this.organizationNames = organizationNames;
    return this;
  }

  public V9VmOpenApiOrganization addOrganizationNamesItem(VmOpenApiLocalizedListItem organizationNamesItem) {
    if (this.organizationNames == null) {
      this.organizationNames = new ArrayList<VmOpenApiLocalizedListItem>();
    }
    this.organizationNames.add(organizationNamesItem);
    return this;
  }

   /**
   * List of organization names. (Max.Length: 100).
   * @return organizationNames
  **/
  @ApiModelProperty(value = "List of organization names. (Max.Length: 100).")
  public List<VmOpenApiLocalizedListItem> getOrganizationNames() {
    return organizationNames;
  }

  public void setOrganizationNames(List<VmOpenApiLocalizedListItem> organizationNames) {
    this.organizationNames = organizationNames;
  }

  public V9VmOpenApiOrganization displayNameType(List<VmOpenApiNameTypeByLanguage> displayNameType) {
    this.displayNameType = displayNameType;
    return this;
  }

  public V9VmOpenApiOrganization addDisplayNameTypeItem(VmOpenApiNameTypeByLanguage displayNameTypeItem) {
    if (this.displayNameType == null) {
      this.displayNameType = new ArrayList<VmOpenApiNameTypeByLanguage>();
    }
    this.displayNameType.add(displayNameTypeItem);
    return this;
  }

   /**
   * List of Display name types (Name or AlternativeName) for each language version of OrganizationNames.
   * @return displayNameType
  **/
  @ApiModelProperty(value = "List of Display name types (Name or AlternativeName) for each language version of OrganizationNames.")
  public List<VmOpenApiNameTypeByLanguage> getDisplayNameType() {
    return displayNameType;
  }

  public void setDisplayNameType(List<VmOpenApiNameTypeByLanguage> displayNameType) {
    this.displayNameType = displayNameType;
  }

  public V9VmOpenApiOrganization areaType(String areaType) {
    this.areaType = areaType;
    return this;
  }

   /**
   * Area type (Nationwide, NationwideExceptAlandIslands, LimitedType).
   * @return areaType
  **/
  @ApiModelProperty(value = "Area type (Nationwide, NationwideExceptAlandIslands, LimitedType).")
  public String getAreaType() {
    return areaType;
  }

  public void setAreaType(String areaType) {
    this.areaType = areaType;
  }

  public V9VmOpenApiOrganization areas(List<VmOpenApiArea> areas) {
    this.areas = areas;
    return this;
  }

  public V9VmOpenApiOrganization addAreasItem(VmOpenApiArea areasItem) {
    if (this.areas == null) {
      this.areas = new ArrayList<VmOpenApiArea>();
    }
    this.areas.add(areasItem);
    return this;
  }

   /**
   * List of organization areas.
   * @return areas
  **/
  @ApiModelProperty(value = "List of organization areas.")
  public List<VmOpenApiArea> getAreas() {
    return areas;
  }

  public void setAreas(List<VmOpenApiArea> areas) {
    this.areas = areas;
  }

  public V9VmOpenApiOrganization organizationDescriptions(List<VmOpenApiLocalizedListItem> organizationDescriptions) {
    this.organizationDescriptions = organizationDescriptions;
    return this;
  }

  public V9VmOpenApiOrganization addOrganizationDescriptionsItem(VmOpenApiLocalizedListItem organizationDescriptionsItem) {
    if (this.organizationDescriptions == null) {
      this.organizationDescriptions = new ArrayList<VmOpenApiLocalizedListItem>();
    }
    this.organizationDescriptions.add(organizationDescriptionsItem);
    return this;
  }

   /**
   * Localized list of organization descriptions. (Max.Length: 2500 Description). (Max.Length: 150 ShortDescription).
   * @return organizationDescriptions
  **/
  @ApiModelProperty(value = "Localized list of organization descriptions. (Max.Length: 2500 Description). (Max.Length: 150 ShortDescription).")
  public List<VmOpenApiLocalizedListItem> getOrganizationDescriptions() {
    return organizationDescriptions;
  }

  public void setOrganizationDescriptions(List<VmOpenApiLocalizedListItem> organizationDescriptions) {
    this.organizationDescriptions = organizationDescriptions;
  }

  public V9VmOpenApiOrganization emails(List<V4VmOpenApiEmail> emails) {
    this.emails = emails;
    return this;
  }

  public V9VmOpenApiOrganization addEmailsItem(V4VmOpenApiEmail emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<V4VmOpenApiEmail>();
    }
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * List of email addresses.
   * @return emails
  **/
  @ApiModelProperty(value = "List of email addresses.")
  public List<V4VmOpenApiEmail> getEmails() {
    return emails;
  }

  public void setEmails(List<V4VmOpenApiEmail> emails) {
    this.emails = emails;
  }

  public V9VmOpenApiOrganization phoneNumbers(List<V4VmOpenApiPhone> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public V9VmOpenApiOrganization addPhoneNumbersItem(V4VmOpenApiPhone phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<V4VmOpenApiPhone>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

   /**
   * List of organizations phone numbers.
   * @return phoneNumbers
  **/
  @ApiModelProperty(value = "List of organizations phone numbers.")
  public List<V4VmOpenApiPhone> getPhoneNumbers() {
    return phoneNumbers;
  }

  public void setPhoneNumbers(List<V4VmOpenApiPhone> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }

  public V9VmOpenApiOrganization webPages(List<V9VmOpenApiWebPage> webPages) {
    this.webPages = webPages;
    return this;
  }

  public V9VmOpenApiOrganization addWebPagesItem(V9VmOpenApiWebPage webPagesItem) {
    if (this.webPages == null) {
      this.webPages = new ArrayList<V9VmOpenApiWebPage>();
    }
    this.webPages.add(webPagesItem);
    return this;
  }

   /**
   * List of organizations web pages.
   * @return webPages
  **/
  @ApiModelProperty(value = "List of organizations web pages.")
  public List<V9VmOpenApiWebPage> getWebPages() {
    return webPages;
  }

  public void setWebPages(List<V9VmOpenApiWebPage> webPages) {
    this.webPages = webPages;
  }

  public V9VmOpenApiOrganization addresses(List<V9VmOpenApiAddress> addresses) {
    this.addresses = addresses;
    return this;
  }

  public V9VmOpenApiOrganization addAddressesItem(V9VmOpenApiAddress addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<V9VmOpenApiAddress>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * List of organizations addresses.
   * @return addresses
  **/
  @ApiModelProperty(value = "List of organizations addresses.")
  public List<V9VmOpenApiAddress> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<V9VmOpenApiAddress> addresses) {
    this.addresses = addresses;
  }

  public V9VmOpenApiOrganization electronicInvoicings(List<VmOpenApiOrganizationEInvoicing> electronicInvoicings) {
    this.electronicInvoicings = electronicInvoicings;
    return this;
  }

  public V9VmOpenApiOrganization addElectronicInvoicingsItem(VmOpenApiOrganizationEInvoicing electronicInvoicingsItem) {
    if (this.electronicInvoicings == null) {
      this.electronicInvoicings = new ArrayList<VmOpenApiOrganizationEInvoicing>();
    }
    this.electronicInvoicings.add(electronicInvoicingsItem);
    return this;
  }

   /**
   * List of organizations electronic invoicing information.
   * @return electronicInvoicings
  **/
  @ApiModelProperty(value = "List of organizations electronic invoicing information.")
  public List<VmOpenApiOrganizationEInvoicing> getElectronicInvoicings() {
    return electronicInvoicings;
  }

  public void setElectronicInvoicings(List<VmOpenApiOrganizationEInvoicing> electronicInvoicings) {
    this.electronicInvoicings = electronicInvoicings;
  }

  public V9VmOpenApiOrganization publishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
    return this;
  }

   /**
   * Publishing status (Draft, Published, Deleted or Modified).
   * @return publishingStatus
  **/
  @ApiModelProperty(required = true, value = "Publishing status (Draft, Published, Deleted or Modified).")
  public String getPublishingStatus() {
    return publishingStatus;
  }

  public void setPublishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
  }

  public V9VmOpenApiOrganization services(List<V5VmOpenApiOrganizationService> services) {
    this.services = services;
    return this;
  }

  public V9VmOpenApiOrganization addServicesItem(V5VmOpenApiOrganizationService servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<V5VmOpenApiOrganizationService>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * List of organizations services.
   * @return services
  **/
  @ApiModelProperty(value = "List of organizations services.")
  public List<V5VmOpenApiOrganizationService> getServices() {
    return services;
  }

  public void setServices(List<V5VmOpenApiOrganizationService> services) {
    this.services = services;
  }

  public V9VmOpenApiOrganization modified(@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Date when item was modified/created (UTC).
   * @return modified
  **/
  @ApiModelProperty(value = "Date when item was modified/created (UTC).")
  public @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.datatype.jsr310.ser.OffsetDateTimeSerializer.class) @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = fi.metatavu.ptv.client.OffsetDateTimeDeserializer.class) java.time.OffsetDateTime modified) {
    this.modified = modified;
  }

  public V9VmOpenApiOrganization subOrganizations(List<VmOpenApiItem> subOrganizations) {
    this.subOrganizations = subOrganizations;
    return this;
  }

  public V9VmOpenApiOrganization addSubOrganizationsItem(VmOpenApiItem subOrganizationsItem) {
    if (this.subOrganizations == null) {
      this.subOrganizations = new ArrayList<VmOpenApiItem>();
    }
    this.subOrganizations.add(subOrganizationsItem);
    return this;
  }

   /**
   * The sub organizations
   * @return subOrganizations
  **/
  @ApiModelProperty(value = "The sub organizations")
  public List<VmOpenApiItem> getSubOrganizations() {
    return subOrganizations;
  }

  public void setSubOrganizations(List<VmOpenApiItem> subOrganizations) {
    this.subOrganizations = subOrganizations;
  }

  public V9VmOpenApiOrganization responsibleOrganizationId(UUID responsibleOrganizationId) {
    this.responsibleOrganizationId = responsibleOrganizationId;
    return this;
  }

   /**
   * Responsible organization identifier if exists.
   * @return responsibleOrganizationId
  **/
  @ApiModelProperty(value = "Responsible organization identifier if exists.")
  public UUID getResponsibleOrganizationId() {
    return responsibleOrganizationId;
  }

  public void setResponsibleOrganizationId(UUID responsibleOrganizationId) {
    this.responsibleOrganizationId = responsibleOrganizationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V9VmOpenApiOrganization v9VmOpenApiOrganization = (V9VmOpenApiOrganization) o;
    return Objects.equals(this.id, v9VmOpenApiOrganization.id) &&
        Objects.equals(this.sourceId, v9VmOpenApiOrganization.sourceId) &&
        Objects.equals(this.oid, v9VmOpenApiOrganization.oid) &&
        Objects.equals(this.parentOrganizationId, v9VmOpenApiOrganization.parentOrganizationId) &&
        Objects.equals(this.organizationRootId, v9VmOpenApiOrganization.organizationRootId) &&
        Objects.equals(this.municipality, v9VmOpenApiOrganization.municipality) &&
        Objects.equals(this.organizationType, v9VmOpenApiOrganization.organizationType) &&
        Objects.equals(this.businessCode, v9VmOpenApiOrganization.businessCode) &&
        Objects.equals(this.businessName, v9VmOpenApiOrganization.businessName) &&
        Objects.equals(this.organizationNames, v9VmOpenApiOrganization.organizationNames) &&
        Objects.equals(this.displayNameType, v9VmOpenApiOrganization.displayNameType) &&
        Objects.equals(this.areaType, v9VmOpenApiOrganization.areaType) &&
        Objects.equals(this.areas, v9VmOpenApiOrganization.areas) &&
        Objects.equals(this.organizationDescriptions, v9VmOpenApiOrganization.organizationDescriptions) &&
        Objects.equals(this.emails, v9VmOpenApiOrganization.emails) &&
        Objects.equals(this.phoneNumbers, v9VmOpenApiOrganization.phoneNumbers) &&
        Objects.equals(this.webPages, v9VmOpenApiOrganization.webPages) &&
        Objects.equals(this.addresses, v9VmOpenApiOrganization.addresses) &&
        Objects.equals(this.electronicInvoicings, v9VmOpenApiOrganization.electronicInvoicings) &&
        Objects.equals(this.publishingStatus, v9VmOpenApiOrganization.publishingStatus) &&
        Objects.equals(this.services, v9VmOpenApiOrganization.services) &&
        Objects.equals(this.modified, v9VmOpenApiOrganization.modified) &&
        Objects.equals(this.subOrganizations, v9VmOpenApiOrganization.subOrganizations) &&
        Objects.equals(this.responsibleOrganizationId, v9VmOpenApiOrganization.responsibleOrganizationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceId, oid, parentOrganizationId, organizationRootId, municipality, organizationType, businessCode, businessName, organizationNames, displayNameType, areaType, areas, organizationDescriptions, emails, phoneNumbers, webPages, addresses, electronicInvoicings, publishingStatus, services, modified, subOrganizations, responsibleOrganizationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V9VmOpenApiOrganization {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    oid: ").append(toIndentedString(oid)).append("\n");
    sb.append("    parentOrganizationId: ").append(toIndentedString(parentOrganizationId)).append("\n");
    sb.append("    organizationRootId: ").append(toIndentedString(organizationRootId)).append("\n");
    sb.append("    municipality: ").append(toIndentedString(municipality)).append("\n");
    sb.append("    organizationType: ").append(toIndentedString(organizationType)).append("\n");
    sb.append("    businessCode: ").append(toIndentedString(businessCode)).append("\n");
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    organizationNames: ").append(toIndentedString(organizationNames)).append("\n");
    sb.append("    displayNameType: ").append(toIndentedString(displayNameType)).append("\n");
    sb.append("    areaType: ").append(toIndentedString(areaType)).append("\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("    organizationDescriptions: ").append(toIndentedString(organizationDescriptions)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    webPages: ").append(toIndentedString(webPages)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    electronicInvoicings: ").append(toIndentedString(electronicInvoicings)).append("\n");
    sb.append("    publishingStatus: ").append(toIndentedString(publishingStatus)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    subOrganizations: ").append(toIndentedString(subOrganizations)).append("\n");
    sb.append("    responsibleOrganizationId: ").append(toIndentedString(responsibleOrganizationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

