/**
 * PTV Open Api
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package fi.metatavu.ptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import fi.metatavu.ptv.client.model.VmOpenApiLanguageItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * VmOpenApiOrganizationEmailIn
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-25T15:52:10.525+02:00")
public class VmOpenApiOrganizationEmailIn   {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("descriptions")
  private List<VmOpenApiLanguageItem> descriptions = new ArrayList<VmOpenApiLanguageItem>();

  public VmOpenApiOrganizationEmailIn email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email address.
   * @return email
  **/
  @ApiModelProperty(example = "null", required = true, value = "Email address.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public VmOpenApiOrganizationEmailIn descriptions(List<VmOpenApiLanguageItem> descriptions) {
    this.descriptions = descriptions;
    return this;
  }

  public VmOpenApiOrganizationEmailIn addDescriptionsItem(VmOpenApiLanguageItem descriptionsItem) {
    this.descriptions.add(descriptionsItem);
    return this;
  }

   /**
   * Localized list of descriptions for the email address.
   * @return descriptions
  **/
  @ApiModelProperty(example = "null", value = "Localized list of descriptions for the email address.")
  public List<VmOpenApiLanguageItem> getDescriptions() {
    return descriptions;
  }

  public void setDescriptions(List<VmOpenApiLanguageItem> descriptions) {
    this.descriptions = descriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VmOpenApiOrganizationEmailIn vmOpenApiOrganizationEmailIn = (VmOpenApiOrganizationEmailIn) o;
    return Objects.equals(this.email, vmOpenApiOrganizationEmailIn.email) &&
        Objects.equals(this.descriptions, vmOpenApiOrganizationEmailIn.descriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, descriptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VmOpenApiOrganizationEmailIn {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    descriptions: ").append(toIndentedString(descriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

